spring.application.name=backend

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/phonebook
spring.datasource.username=coder2client
spring.datasource.password=pastoral2u
spring.datasource.driver-class-name=org.postgresql.Driver
